services:
  ExcelBotCs:
    image: excelbotcs
    build:
      context: .
      dockerfile: ExcelBotCs/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      DATABASE_NAME: ${DATABASE_NAME:-excelbotcs}
      DISCORD_CONFIG: ${DISCORD_CONFIG}
      LOTTERY_CHANNEL: ${LOTTERY_CHANNEL}
      EVENT_ENDPOINT_URL: ${EVENT_ENDPOINT_URL:-localhost:8080}

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_ENABLED: ${ME_CONFIG_BASICAUTH_ENABLED:-true}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}